* Namespaces
  There are six kinds of names in haskell.
  1. Variables
  2. Constructors
  3. Type Variables
  4. Type Constructors
  5. Type Classes
  6. Modules
  The names of variables and type variables begin with lower case letters. All
  other names begin with upper case letters.
  An identifier must not be used as the name of a type constructor and a class
  in same scope.
* Free Variable
  A variable that is not bound is called a /free variable/.

  #+BEGIN_SRC haskell
    (\x -> x y)
  #+END_SRC
  
  In above code y is free variable. Wether the variable is free or not depends
  upon context in which expression is evaluated.
* Thunk
  A /thunk/ is unevaluated expression. It is used in haskell system that
  implements non-strict semantics by lazy evaluation. A lazy run-time system
  doesnt evaluate a thunk unless it has to. Expressions are translated into a
  graph (not a tree this enables sharing and infinite lists) and a Spineless
  Tagless G-machine /reduces/ it chuking out any unneeded thunk, unevaluated.
* Modules
  A haskell module consist of many of the various declarations which occur in
  arbitray order but import declarations must appear first. The declarations are
  fixity declarations, data and type declarations, class and instance
  declarations, type signatures, function definitions and pattern bindings. 
  A haskell program consist of collection of *modules*. A module in haskell
  serve the dual purpose of *controlling namespaces* and *creating abstract*
  *data types*. Modules are not *first-class*. Modules names are alphanumeric
  and must begin with Uppercase letter. Namespace of modules is flat.
  Techinically speaking module is one big declaration which begins with keyword
  module. 
* Declarations vs Expressions
  There are two ways of writing functional programs and both the style are
  supported by Haskell
** Declarations
   One Formulate an alogrithm in terms of several equations that shall be satisfied
** Expressions
   One compose big expressions from small expressions
* IO
  Haskell IO system is built on daunting mathematical foundation: *monads*.
* Types, Values
  Haskell is a purely functional language therefore all computations are done by
  evaluating *expressions* to yield a *value*. Every value has an associated
  *static* type. Intitutively we can think of types as set of values. All well
  formed expression has types and are found at compile time by a process called
  type inference.

  *Type Expression* denote type values or just types. Haskell types are not first
  class.

  Function in Haskell are normally defined as series of equations. A function
  can be defined by the single equation as follows
  
  #+begin_src haskell
    inc :: Num => a -> Integer
    inc c = c + 1
  #+end_src

  An equation is an example of declaration. Another kind of declaration is type
  expression declaration.

  #+begin_src haskell
      inc :: Integer -> Integer
  #+end_src
** Polymorphic Types
   Haskell also incorporates polymorphic types--types that are universally
   quantified over all types. Polymorphic type expressions essentially describe
   families of types. Identifiers such as above are called *type variables*.

   With polymorphic types some types are more *general* than others. For
   instance [a] is more general than [Char]. In other words latter type can be
   derived from former by suitable substitution for a. Haskell type system has
   two important properties:
   1. Every well typed expression is gauranteed to have unique *principal* type.
   2. Principal type can be inferred automatically

** User Defined Types
   We can define our own types using *data* declaration.

** Data Constructor and Type Constructor
   Consider the following sippet of code which declares an algerbriac data type
   called LispVal

   #+begin_src haskell

     data LispVal = Atom String
       | List [LispVal]
       | DottedList [LispVal] LispVal
       | Number Integer
       | String String
       | Bool Bool

   #+end_src 

   Data Constructor and type have different namespaces, so they can
   have same name.
* I/O Actions
  When Programming in Haskell and we want to do something that has a side
  effect, something that affects the world in some ways, we use
  *actions*. *Actions are values* in the haskell language, much like number
  three, the string "hello world" or the function ~map~. They can be bound to
  variable, passed to function and can be result of functions.

  Like other haskell value every action has a type. There are many kind of
  actions of which IO Action is one used for input and output. The type of
  action reflects kind of action (IO) as well as type of value it provides as a
  result. Infact all IO actions will have a type IO a for some type a. When an
  action doesn't provide any useful data back to the program the unit type
  (written ()) is used to denote the result.

  While actions can result in values which are used by the program, they donot
  take any arguments. Consider ~putStrln~ its type is
  ~putStrln :: [Char] -> IO ()~
  putStrln takes an argument but it is not an action its a function. It takes
  one argument and return an action of type IO (). But ~putStrln "Hello"~ is an
  action. Action are like directions. They specify something that can be
  done. They are not active in and of themselves. They need to be "run" to make
  something happen. Since ~putstrln "Hello"~ is an action we can store it in a
  variable like any other value.
  #+begin_src haskell
      x = putStrLn "Hello"
  #+end_src
  Haskell only run one IO action in a program, the action is called ~main~.
  
** ~do~ block
   We can combine simple actions to  perform complex actions. To combine actions
   into a single action we use ~do~ block. When two IO actions are combined the
   result is an IO action that, when invoked, performs the first action and then
   performs the second action. If the first action has any side affects those
   effects are visible to the second action when it is performed. IO actions can
   return result to the program. For instance ~getLine~ returns line to the
   program.

   #+begin_src haskell
     main :: IO ()
     main = do
       x <- getLine
       putStrLn $ "You said " ++ x
   #+end_src

   Notice ~<-~ is used to bind and not an equal sign. The arrow indicates the
   result of an action is being bound.

   #+begin_src haskell
     promptLine prompt = do
       putStrLn "Enter the line"
       getLine

     main :: IO ()
     main = do
       line <- promptLine "Enter the line"
       putStrLn $ "You said " ++ line
   #+end_src

   ~promptLine~ returns an action whose type is the result of last action,
   ~getLine~.

   In general we use ~<<~ if the actions don't return a value, ~>>=~ if you will
   be immidiately passing that value into the next action and do-notation
   otherwise. Rememeber each line of do block must have same type.

* Combinators
  In haskell combinator pattern is populary used to describe the idea of
  organizing libraries centered around the idea of combining things. Usually
  there is some type T, some functions for constructing primitive values of type
  T, and some combinators which can combine values of type T in various ways to
  build complex values of type T.
* Pattern Matching
  Patterns are not first class; there are only a fixed set of different kinds of
  pattern. There is data constructor pattern.

  Technically speaking formal parameters are also patterns-It is just that they
  never fail to match a value. A side effect to successful matching is that they
  are bound to value it is being matched against. Patterns which never fail to
  match are called irreffutable in contrast to refutable pattern which fails to
  match. There are three other kinds of irrefutable pattern.

** As Pattern
   Consider the following code snippet

   #+begin_src haskell
     f (x:xs) = x:x:xs

     f @s(x:xs) = x:s
   #+end_src

** Wild Cards
   They match anything but in case of formal parameters binds nothing.

** Pattern Matching Semantics
   Pattern Matching can succeed, fail or diverge.
   *A sequence of gaurds provied for same pattern* as follows

   #+begin_src haskell
     sign x | x > 0 = 1
            | x == 0 = 0
            | x < 0 = -1
   #+end_src

* Case Expression
  Pattern Matching provides a way to dispatch control based upon structural
  properties of a value.
* Function in Haskell
  Below are some examples for writing functions in Haskell.
  It demonstrates use of if-else, case and gaurds.
  The code snippet below shows an example of recursive factorial procedure which
  evolves into recursive process

  #+begin_src haskell
    factorialIf num = if (num == 0) || (num == 1)
                      then 1
                      else num * factorialIf (num - 1)

    factorialCase num = case num of 0 -> 1
                                    1 -> 1
                                    _ -> num * factorialCase (num - 1)


    factorialGaurds num | num == 0 = 1
                        | num == 1 = 1
                        | otherwise = num *factorialGaurds (num - 1)          
  #+end_src

  The code snippet below is an example of recursive factorial procedre which
  evolves into an iterative process.
  
  #+begin_src haskell
    factorialIter num = factIterative 1 1 num
      where factIterative result counter num = if counter > num
                                               then result
                                               else factIterative (result * counter) (counter + 1) num

  #+end_src
* Folds
* Monads
  When complexity reaches a certain level, we start decomposing larger
  computations into smaller ones. The quality of decomposition is measured by
  how much coupling there is between the pieces, and how well we and the
  compiler can control and verify it. There is overwhelming evidence that hidden
  couplings are a major source of bugs in both single and multithreaded
  programs. 
  Pure functional programming reduces the coupling to the minimum--its just
  plugging output of one function into another. However many traditional notions
  of computations are expressed in a pseudo functional way;with procedures that
  take arguments and return result but also do some non-functional things. There
  is surprisingly large class of such computations that can be truned into pure
  functions by just modifying their return types.

  A pure function is well behaved;if we give a function a certain input it will
  always generate exactly same output.

  A Monad turns out to be a key of writing *side-effecting* programs in pure
  functional languages. With monads we can use the type system to cleanly
  separate out side effecting computations from ones that don't have a side
  effect so that niether kind of computation interfere with other. So we get
  all the benefits of functional programming for code that doesn't do
  side-effects (type system gaurantees that they don't do side effects) while
  still being able to do side effects when necessary.

  *Monads are general tool for structuring various kinds of computation* in a
  well behaved way. In many cases monadic code can be vastly shorter and more 
  comprehensible than equivalent non-monadic code. So monads have an
  applicability that goes way beyond helping us deal with side-effects in
  functional languages.

  *Monads are generalization of functions, function application, and function*
  *composition to allow them to deal with richer notions of computation than*
  *standard function.*
  
  What is *Notions of Computations*?
  The simplest and well behaved notion of computation is ordinary (pure)
  functions. A pure function is a rule which for a particular input always
  generate exact same output. In Haskell function have well defined type
  signature which means there are types a and b such that function maps a value
  of type a to a value of type b. We can express this in Haskell notation as
  follows
  
  #+begin_src haskell
    f :: a -> b
  #+end_src
  
  where the ~::~ means "has the following type". So the function has the
  functional type ~a -> b~, which means that it takes in a value of type a and
  returns a value of type b.
  Some other notions of computations (also refered to as side effects)
  1. may do file or terminal input/output
  2. may raise exceptions
  3. may read or write shared state(local or gloabl)
  4. may fail to produce any results
  5. may produce multiple results at the same time.

  A /monad/ describes the way of transforming the return type of a particular
  kind of computation into a fancier /monadic type/. Functions that return a
  monadic type are called monadic functions.
  ~do~ notation simplifies the syntax of composing multiple monadic functions.

  The *IO system* in Haskell and many other functional languages is constructed
  using a Monad.

  The Prelude contains a number of classes defining monads as they are used in
  Haskell. These classes are based upon monad construct in *category theory*
  While the category theoretic terminology provides the names of monadic
  classes and operations, it is not necessary to delve into abstract mathematics
  to get an intutive understanding of how to use monadic classes.
** Monadic Values and Monadic Functions
   The point of monads is to generalize the notion of function application and
   function compositions to notions of computation which are different from pure
   functions. We might want to write the type of this extended function
   something like below

   #+begin_src haskell
     f :: a --[something else] --> b
   #+end_src

   for extended function f, input type a and output type b. The /something else/
   is specific to particuar notion of computation. In Haskell special notion of
   computation correspond to particular monad. We can refer to these functions
   as monadic functions.

   In Haskell monads always have the form

   #+begin_src haskell
     f :: a -> mb
   #+end_src
   
   In code above f is a pure function which takes input value of type a and
   returns output value of type mb. So in Haskell these monadic functions are
   represented as pure functions with a funky monadic return type;put
   differently, the pure function takes in regular values and return funky
   "monadic values". In notation "m b" b is some Haskell type, and m will
   represent some kind of monad. In Haskell m has to be /type constructor/,
   which is basically function on types. It takes type argument and returns a
   new type. *Generally we say that f is a function from a to b in IO monad.*

   Note: There is related notion called comonad which uses function like ~f:: c
   a -> b~ for some comonad c.

   Consider the /notion of/ list  of Int. The /list of/ part can be thought as a
   type constructor which takes a particular type ~Int~ as and returns new type
   ~[Int]~. Infact any polymorphic type in Haskell has a corresponding type
   constructor.
   One the simplest is polymorphic ~Maybe~ type.

   #+begin_src haskell
     data Maybe a = Just a | Nothing   
   #+end_src 
   
   which says ~Maybe~ is a type constructor which takes input ~a~ which is a
   type and and produces another type as output. For example
   
   #+begin_src haskell
     data Maybe Int = Just Int | Nothing
   #+end_src
   
   So ~Maybe~ itself is a function on types mapping one input type to output
   type. There is a techincal name for this: the type constructor ~Maybe~ has
   the kind * -> *. A kind is type of types; primitive types have the kind *,
   which just means that they aren't type functions (i.e. type constructors)
   
   So Monads, as represented in Haskell are type constructors turning input type
   into new type. So the ~IO~ monad is a type constructor and IO String, IO Bool
   are valid haskell types. Similarly ~Maybe~ is a type constructor and ~Maybe
   Bool~, ~Maybe Int~ are valid Haskell types.

   *Note:* Monads in Haskell are type constructors;not all type constructors are
   monads. As we will se Monads have to be type constructors for which specific
   operations are defined and for which specific monad laws hold.

   *Big Question* What does values that have monadic type represents. Lets call
   them *monadic values*(not standard terminology). What does value of ~IO
   float~ or ~IO String~ represent.

   *Recap*
   1. There is familiar concept of pure functions;a function which does nothing
      more than converting an input value of some type to an output value.
   2. Then there are special kinds of functions that do something else besides
      converting input values into output values. That something else do file IO
      or terminal IO, raise exceptions, interacting with local or global state,
      possibly fail, or return more than one result etc. Each of these special
      kinds of function corresponds to particular monad. Let's refer them as
      *monadic functions*.
   3. Haksell represents monadic functions as pure functions which convert input
      value of some type into an output value of special monadic type. Let's
      call these output values as *monadic values*.

      *Problem Restatement*
      What do monadic values really represent?.
      *Answer* They dont really represent anything intutive. The intutive
      concept is notion of monadic functions. The concept of monadic value is
      not intutive;its just how haskell has chosen to represent the output of
      monadic functions.

   Nevertheless in Haskell there two ways of trying to explain the notion of
   monadic value
   1. A monadic value of type ~m a~ is some kind of action that does /something
      else/ and returns value of type a.
   2. A monadic value of type a is like a container that stores value of type
      a. 

   Let's take our notion of monadic functions as our starting point.

   #+begin_src haskell
     f :: a -> mb
   #+end_src

   Then ~f x~, where x has type a, would have type ~m b~

   ~x :: a~
   ~f x :: m b~

   Now ~f x~ is a monadic value which is not very intutive.
   Consider another function ~g~ as follows
   #+begin_src haskell
     g :: a -> () -> a
     g x () = x
   #+end_src

   ~g (f x)~ has type ~() -> m b~. In other words, its a function which takes a
   unit value as argument and returns monadic value. But looked at another way,
   its a monadic function which converts a unit value into a value of type b
   also doing something else in the process.

   We can understand the monadic value construct in Haskell in a way that it is
   a function of type ~() -> m b~ i.e. a function which maps unit value to a
   value of type ~b~ doing something else in the process.

** Fundamental Monadic Operation
   One of the keys in functional programming is the ability to compose new
   functions. Functional Programmers talk about /composability/ all the time,
   with the implication that if some aspect of a programming language isn't
   composable, its probably not worth much.

   In Haskell we use the type system to give us gaurantee that pure functions
   are actually pure. It also means that there is no ~extract~ functions such
   that 

   ~extract :: IO b -> b~

   If such a function exists, it will allow us to construct a pure function from
   monadic functions which will destory the purity of Haskell.

   ~f :: a -> IO b~
   ~g :: b -> IO c~
   ~h :: a -> c~

   ~h = g . extract . f~

   Now if we have a function ~mapply~ with the following type signature
   
   ~mapply :: IO b -> (b -> IO c) -> IO c~

   we can compose two monadic functions f and g in the following way

   ~f :: a -> IO b~
   ~g :: b -> IO c~
   
   Our goal is to compose a function ~h~ from ~f~ and ~g~ such that
   
   ~h = f `mcompose` g~

   ~h x = mapply (f x) g~

   ~mcompose f g x = (f x) `mapply`  g~

   ~mapply~ is one of the two fundamental monadic oprations. It is normally
   called *bind* and is written as infix operator with symbol ~>>=~.

   ~>>= :: m a -> (a -> mb) -> m b~

   where a is any type and m is any monadic type constructor.

   Using >>= operator we can write h as follows
   
   ~h = f x >>= g~

   Suppose we want to compose a monadic function with non-monadic function.

   ~f :: a -> mb~
   ~g :: b -> c~

   With the ~extract~ function we can compose function as follows to get a pure
   function

   ~h = g . extract . f~

   But we are not allowed to do this. if we have a ~return~ function as follows
   
   ~return :: (b -> c) -> (b -> m c)~

   then we can compose function f and g in the following way

   ~h  = f >=> (return . g)~

** Monad type class
   Following code snippet is the full declaration of full monadic type class.

   #+begin_src haskell
        class Monad m where
          (>>=) :: m a -> (a -> mb) -> mb
          return :: a -> m a
          (>>) :: m a -> m b -> m b
          fail :: String -> m a
   #+end_src

*** Monadic Laws
    1. return >=> f == f (return is an identity for monadic composition)
    2. f >=> return == f 
    3. (f >=> g) >=> h == f >=> (g >=> h) (monadic composition is associative)

    
    
* Operator
** Operator Associativity
   
** Bind Operator (>>)
   It is used behind the scenes of a ~do~ block to combine sequence of actions.
* Algebraic Data Types  
* TypeClasses
  Class methods are treated as top level declaration in Haskell. They share
  same namespace as ordinary variables; a name cannot be used to denote both a
  class method and a variable or method in different class. TypeClasses admit
  adhoc polymorphism or overloading.
  ~Read~ and ~Show~ typeclasses are used for serilization in Haskell. ~show~
  method of ~Show~ typeclass produces output that is both human readable and
  machine readable and ~read~ method of ~Read~ typeclass 
* Polymorphism
  A value is polymorphic if there is more than one type it can have. It is key
  feature of Haskell's type system. Two categories of polymorphism
  1. *Parametric Polymorphism*: refers to when the type of value contains one or
     more (unconstrained) type variables, so that value may adopt any type that
     results from substituting those variables with concrete type. In Haskell
     this means any type in which a type variable, denoted by a name in a type
     begininning with a lowercase letter appears without constraints.
  2. *Ad-hoc Polymorphism* is achieved in Haskell using typeclasses and class
     instances.
* Laziness
  In Haskell Non-strict semantics is implemented using Laziness.
  *String Handling in Haskell is normally lazy, so ~read~ and ~show~ can be used
  on quite large data structures without incident.
* Currying
  
